<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Broiler.Media.Video.MediaFoundation" Version="0.1.0-preview.13" />
    <PackageVersion Include="Broiler.Media.Video.Windows" Version="0.1.0-preview.13" />
    <PackageVersion Include="Broiler.Native.Linux" Version="0.1.0-preview.3" />
    <PackageVersion Include="Broiler.Native.Windows" Version="0.1.0-preview.3" />
  </ItemGroup>
</Project>
